# Generated by Django 5.0 on 2024-11-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_users_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyassignment',
            name='status',
            field=models.CharField(choices=[('CHECKED_OUT', 'Checked Out'), ('CHECKED_IN', 'Checked In'), ('LOST', 'Lost')], default='CHECKED_OUT', max_length=15),
        ),
    ]
